
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { HRTool, HRAnalysis, EmergingTechnology } from './types';
import { fetchHRTools, fetchHRAnalysis, fetchDEITools } from './services/geminiService';
import Header from './components/Header';
import Footer from './components/Footer';
import LoadingSpinner from './components/LoadingSpinner';
import ToolCard from './components/ToolCard';
import ToolDetailModal from './components/ToolDetailModal';
import ComparisonModal from './components/ComparisonModal';
import AddToolModal from './components/AddToolModal';

const RATINGS_STORAGE_KEY = 'hrToolRatings';
const FAVORITES_STORAGE_KEY = 'hrToolFavorites';
const USER_TOOLS_STORAGE_KEY = 'hrToolUserAdded';

// --- Analysis Display Component ---
interface AnalysisDisplayProps {
  analysis: HRAnalysis;
}

const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ analysis }) => {
  return (
    <section className="mb-16 rounded-3xl overflow-hidden shadow-2xl border border-white/20 relative group">
      {/* Glass background effect */}
      <div className="absolute inset-0 bg-slate-900 z-0"></div>
      <div className="absolute inset-0 bg-gradient-to-br from-indigo-900/50 to-slate-900/80 z-0"></div>
      <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-indigo-600/20 rounded-full blur-[100px] pointer-events-none -translate-y-1/2 translate-x-1/3"></div>

      <div className="relative z-10 p-8 md:p-12 text-white">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-10 border-b border-white/10 pb-6">
          <div>
            <span className="text-indigo-400 font-bold tracking-wider uppercase text-xs mb-2 block">Market Intelligence</span>
            <h2 className="text-3xl md:text-4xl font-bold text-white">
              AI in HR: 2026 Outlook
            </h2>
          </div>
          <div className="text-slate-400 text-sm max-w-md text-right hidden md:block">
            Generated by Gemini 2.5 Pro • Predictive Analysis
          </div>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16">
          <div className="space-y-8">
            <div>
              <h3 className="text-xl font-semibold text-indigo-200 mb-4 flex items-center">
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                Current Impact & Future Growth
              </h3>
              <p className="text-slate-300 leading-relaxed text-lg font-light">{analysis.currentImpact}</p>
              <p className="mt-6 text-slate-300 leading-relaxed text-lg font-light">{analysis.futureGrowth}</p>
            </div>
          </div>

          <div>
            <h3 className="text-xl font-semibold text-indigo-200 mb-6 flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" /></svg>
              Top 5 Emerging Technologies
            </h3>
            <div className="space-y-4">
              {analysis.emergingTechnologies.map((tech: EmergingTechnology, index: number) => (
                <div key={index} className="group/tech p-4 rounded-xl bg-white/5 hover:bg-white/10 transition-colors border border-white/5 hover:border-white/20">
                  <div className="flex justify-between items-start mb-1">
                    <h4 className="font-bold text-white text-lg group-hover/tech:text-indigo-300 transition-colors">{tech.name}</h4>
                  </div>
                  <p className="text-sm text-slate-300 mb-2 opacity-80">{tech.description}</p>
                  <p className="text-xs text-indigo-200 font-medium uppercase tracking-wide mt-2 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-indigo-400"></span>
                    {tech.impact}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};


// --- Main App Component ---
const App: React.FC = () => {
  const [tools, setTools] = useState<HRTool[]>([]);
  const [deiTools, setDeiTools] = useState<HRTool[]>([]);
  const [userTools, setUserTools] = useState<HRTool[]>([]);
  const [analysis, setAnalysis] = useState<HRAnalysis | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedTool, setSelectedTool] = useState<HRTool | null>(null);
  const [sortType, setSortType] = useState<'default' | 'name' | 'category'>('default');
  const [selectedCategory, setSelectedCategory] = useState<'all' | string>('all');
  const [ratings, setRatings] = useState<{ [key: string]: number }>({});
  const [favorites, setFavorites] = useState<string[]>([]);
  
  // Comparison State
  const [comparisonList, setComparisonList] = useState<HRTool[]>([]);
  const [isComparing, setIsComparing] = useState<boolean>(false);
  
  // Add Tool Modal State
  const [isAddModalOpen, setIsAddModalOpen] = useState<boolean>(false);

  // Check for shared tool in URL on mount
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const shareData = params.get('share');
    if (shareData) {
      try {
        const json = decodeURIComponent(atob(shareData));
        const tool = JSON.parse(json);
        if (tool && tool.name && tool.category) {
          setSelectedTool(tool);
        }
      } catch (e) {
        console.error("Error parsing shared tool data:", e);
      }
    }
  }, []);

  const loadData = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      const savedRatings = localStorage.getItem(RATINGS_STORAGE_KEY);
      if (savedRatings) {
        setRatings(JSON.parse(savedRatings));
      }

      const savedFavorites = localStorage.getItem(FAVORITES_STORAGE_KEY);
      if (savedFavorites) {
        setFavorites(JSON.parse(savedFavorites));
      }

      const savedUserTools = localStorage.getItem(USER_TOOLS_STORAGE_KEY);
      if (savedUserTools) {
        setUserTools(JSON.parse(savedUserTools));
      }

      const [fetchedTools, fetchedAnalysis, fetchedDEITools] = await Promise.all([
        fetchHRTools(),
        fetchHRAnalysis(),
        fetchDEITools()
      ]);

      setTools(fetchedTools);
      setAnalysis(fetchedAnalysis);
      setDeiTools(fetchedDEITools);

    } catch (err: any) {
      setError(err.message || 'An unknown error occurred while fetching data.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleRateTool = (toolName: string, newRating: number) => {
    const newRatings = { ...ratings, [toolName]: newRating };
    setRatings(newRatings);
    localStorage.setItem(RATINGS_STORAGE_KEY, JSON.stringify(newRatings));
  };

  const handleToggleFavorite = (toolName: string) => {
    setFavorites(prev => {
      const newFavorites = prev.includes(toolName) 
        ? prev.filter(f => f !== toolName) 
        : [...prev, toolName];
      localStorage.setItem(FAVORITES_STORAGE_KEY, JSON.stringify(newFavorites));
      return newFavorites;
    });
  };

  const handleAddTool = (newTool: HRTool) => {
    const updatedUserTools = [newTool, ...userTools];
    setUserTools(updatedUserTools);
    localStorage.setItem(USER_TOOLS_STORAGE_KEY, JSON.stringify(updatedUserTools));
  };

  // Comparison Logic
  const handleToggleCompare = (tool: HRTool) => {
    setComparisonList(prev => {
      const isSelected = prev.some(t => t.name === tool.name);
      if (isSelected) {
        return prev.filter(t => t.name !== tool.name);
      } else {
        if (prev.length >= 3) {
            alert("You can compare up to 3 tools at a time.");
            return prev;
        }
        return [...prev, tool];
      }
    });
  };

  const clearComparison = () => setComparisonList([]);


  const categories = useMemo(() => {
    const allToolsForCats = [...tools, ...deiTools, ...userTools];
    const uniqueCategories = [...new Set(allToolsForCats.map(tool => tool.category))];
    uniqueCategories.sort();
    return ['all', ...uniqueCategories];
  }, [tools, deiTools, userTools]);
  
  const filteredAndSortedTools = useMemo(() => {
    // Combine generated tools and user added tools for the main list
    let result = [...userTools, ...tools];

    if (selectedCategory !== 'all') {
      result = result.filter(tool => tool.category === selectedCategory);
    }

    if (sortType === 'name') {
      result.sort((a, b) => a.name.localeCompare(b.name));
    } else if (sortType === 'category') {
      result.sort((a, b) => a.category.localeCompare(b.category));
    }
    
    return result;
  }, [tools, userTools, sortType, selectedCategory]);

  const favoriteToolsList = useMemo(() => {
    // Combine all tools to search for favorites
    const allTools = [...userTools, ...tools, ...deiTools];
    // Filter unique tools that are in favorites
    return allTools.filter((tool, index, self) => 
      favorites.includes(tool.name) && 
      index === self.findIndex((t) => t.name === tool.name)
    );
  }, [tools, deiTools, userTools, favorites]);
  
  const handleOpenModal = (tool: HRTool) => {
    setSelectedTool(tool);
    // Clean URL if a share param exists to avoid confusion
    if (window.location.search.includes('share=')) {
        const url = new URL(window.location.href);
        url.searchParams.delete('share');
        window.history.replaceState({}, '', url);
    }
  };

  const handleCloseModal = () => {
    setSelectedTool(null);
    // Clean URL if a share param exists
    if (window.location.search.includes('share=')) {
        const url = new URL(window.location.href);
        url.searchParams.delete('share');
        window.history.replaceState({}, '', url);
    }
  };

  const renderContent = () => {
    if (isLoading) {
      return <LoadingSpinner />;
    }

    if (error) {
      return (
        <div className="text-center bg-white/80 backdrop-blur-md p-12 rounded-3xl shadow-xl border border-red-100 max-w-2xl mx-auto mt-12">
          <div className="w-20 h-20 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-6">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-10 w-10 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-slate-800 mb-2">Service Temporarily Unavailable</h2>
          <p className="text-slate-600 mb-8">
            We're having trouble connecting to the AI service. Please try again in a few moments.
          </p>
          <button
            onClick={loadData}
            className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-xl shadow-lg shadow-indigo-200 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 transition-all active:scale-95"
          >
            Retry Connection
          </button>
        </div>
      );
    }

    return (
      <>
        {analysis && <AnalysisDisplay analysis={analysis} />}
        
        {favoriteToolsList.length > 0 && (
          <section className="my-16 animate-fade-in">
            <div className="flex items-center mb-8">
                <div className="p-2 bg-red-50 rounded-lg mr-4">
                     <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-red-500" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd" />
                    </svg>
                </div>
                <div>
                    <h2 className="text-2xl font-bold text-slate-900">Your Favorites</h2>
                    <p className="text-slate-500 text-sm">Quick access to your saved tools</p>
                </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {favoriteToolsList.map((tool) => (
                <ToolCard 
                  key={tool.name} 
                  tool={tool} 
                  onClick={handleOpenModal}
                  rating={ratings[tool.name] || 0}
                  onRate={(rating) => handleRateTool(tool.name, rating)}
                  isSelected={comparisonList.some(t => t.name === tool.name)}
                  onToggleCompare={handleToggleCompare}
                  isFavorite={favorites.includes(tool.name)}
                  onToggleFavorite={() => handleToggleFavorite(tool.name)}
                />
              ))}
            </div>
            <div className="border-b border-slate-200/60 my-16"></div>
          </section>
        )}

        {deiTools.length > 0 && (
          <section className="my-16">
            <div className="flex items-center justify-between mb-10">
                 <div className="max-w-2xl">
                    <span className="text-fuchsia-600 font-bold tracking-wider uppercase text-xs mb-2 block">Special Feature</span>
                    <h2 className="text-3xl font-bold text-slate-900">DEI Innovation</h2>
                    <p className="mt-3 text-slate-600 text-lg font-light">
                      Specialized tools designed to foster a more diverse, equitable, and inclusive workplace in 2026.
                    </p>
                 </div>
                 <div className="hidden lg:block p-4 rounded-full bg-fuchsia-50 border border-fuchsia-100">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-fuchsia-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                 </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {deiTools.map((tool) => (
                <ToolCard 
                  key={tool.name} 
                  tool={tool} 
                  onClick={handleOpenModal}
                  rating={ratings[tool.name] || 0}
                  onRate={(rating) => handleRateTool(tool.name, rating)}
                  isSelected={comparisonList.some(t => t.name === tool.name)}
                  onToggleCompare={handleToggleCompare}
                  isFavorite={favorites.includes(tool.name)}
                  onToggleFavorite={() => handleToggleFavorite(tool.name)}
                />
              ))}
            </div>
            <div className="border-b border-slate-200/60 my-16"></div>
          </section>
        )}

        <div className="mb-8" id="all-tools">
            <h2 className="text-3xl font-bold text-slate-900 text-center mb-10">
                Explore 2026 Tool Landscape
            </h2>

            {/* Control Panel */}
            <div className="glass-panel rounded-2xl p-2 mb-10 sticky top-4 z-30 transition-all duration-300 shadow-lg">
              <div className="flex flex-col xl:flex-row gap-4 items-center justify-between p-2">
                
                {/* Categories */}
                <div className="flex flex-wrap justify-center xl:justify-start gap-1.5 w-full xl:w-auto">
                    {categories.map(category => (
                      <button
                        key={category}
                        onClick={() => setSelectedCategory(category)}
                        className={`px-4 py-2 text-sm font-medium rounded-xl transition-all duration-200 ${
                            selectedCategory === category 
                            ? 'bg-slate-900 text-white shadow-lg shadow-slate-900/20' 
                            : 'bg-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-900'
                        }`}
                      >
                        {category === 'all' ? 'All Categories' : category}
                      </button>
                    ))}
                </div>

                {/* Separator */}
                <div className="hidden xl:block h-8 w-px bg-slate-200"></div>

                {/* Actions */}
                <div className="flex flex-wrap sm:flex-nowrap items-center gap-4 w-full xl:w-auto justify-center">
                    {/* Add Tool Button */}
                    <button
                        onClick={() => setIsAddModalOpen(true)}
                        className="flex items-center gap-2 px-5 py-2 bg-indigo-600 text-white text-sm font-bold rounded-xl shadow-md hover:bg-indigo-700 transition-all active:scale-95 whitespace-nowrap"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                        </svg>
                        Add Tool
                    </button>

                    {/* Sort */}
                    <div className="flex items-center bg-slate-100/50 p-1 rounded-xl w-full sm:w-auto">
                        <span className="text-xs font-semibold text-slate-400 uppercase px-3 hidden sm:block">Sort:</span>
                        <div className="flex w-full">
                            <button 
                            onClick={() => setSortType('default')} 
                            className={`flex-1 sm:flex-none px-4 py-1.5 text-sm font-medium rounded-lg transition-all ${sortType === 'default' ? 'bg-white text-slate-900 shadow-sm ring-1 ring-black/5' : 'text-slate-500 hover:text-slate-700'}`}>
                            Relevance
                            </button>
                            <button 
                            onClick={() => setSortType('name')} 
                            className={`flex-1 sm:flex-none px-4 py-1.5 text-sm font-medium rounded-lg transition-all ${sortType === 'name' ? 'bg-white text-slate-900 shadow-sm ring-1 ring-black/5' : 'text-slate-500 hover:text-slate-700'}`}>
                            Name
                            </button>
                            <button 
                            onClick={() => setSortType('category')} 
                            className={`flex-1 sm:flex-none px-4 py-1.5 text-sm font-medium rounded-lg transition-all ${sortType === 'category' ? 'bg-white text-slate-900 shadow-sm ring-1 ring-black/5' : 'text-slate-500 hover:text-slate-700'}`}>
                            Category
                            </button>
                        </div>
                    </div>
                </div>
              </div>
            </div>
        </div>

        {filteredAndSortedTools.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredAndSortedTools.map((tool) => (
              <ToolCard 
                key={tool.name} 
                tool={tool} 
                onClick={handleOpenModal}
                rating={ratings[tool.name] || 0}
                onRate={(rating) => handleRateTool(tool.name, rating)}
                isSelected={comparisonList.some(t => t.name === tool.name)}
                onToggleCompare={handleToggleCompare}
                isFavorite={favorites.includes(tool.name)}
                onToggleFavorite={() => handleToggleFavorite(tool.name)}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-20 bg-white/50 rounded-3xl border border-dashed border-slate-300">
            <div className="inline-block p-4 rounded-full bg-slate-100 mb-4">
                 <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
            </div>
            <h3 className="text-xl font-semibold text-slate-800">No tools found</h3>
            <p className="mt-2 text-slate-500">
              Try adjusting your filters or add a new tool manually.
            </p>
            <div className="flex gap-4 justify-center mt-6">
                <button 
                    onClick={() => {setSelectedCategory('all'); setSortType('default');}}
                    className="text-indigo-600 font-medium hover:text-indigo-800 hover:underline"
                >
                    Clear all filters
                </button>
                 <span className="text-slate-300">|</span>
                 <button 
                    onClick={() => setIsAddModalOpen(true)}
                    className="text-indigo-600 font-medium hover:text-indigo-800 hover:underline"
                >
                    Add New Tool
                </button>
            </div>
          </div>
        )}
      </>
    );
  };

  return (
    <div className="min-h-screen flex flex-col relative selection:bg-indigo-100 selection:text-indigo-900">
      <Header />
      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl py-8 pb-32">
        {renderContent()}
      </main>
      
      {/* Floating Comparison Bar */}
      {comparisonList.length > 0 && (
        <div className="fixed bottom-8 left-0 right-0 z-40 animate-fade-in-down pointer-events-none flex justify-center">
            <div className="pointer-events-auto bg-slate-900 text-white p-2 rounded-full shadow-2xl shadow-indigo-900/40 flex items-center pl-6 pr-2 gap-6 border border-slate-700">
                    <div className="flex items-center gap-3">
                         <span className="flex h-2 w-2 relative">
                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                            <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500"></span>
                        </span>
                        <span className="text-sm font-medium text-slate-200">
                            <span className="text-white font-bold">{comparisonList.length}</span> {comparisonList.length === 1 ? 'tool' : 'tools'} selected
                        </span>
                    </div>
                    <div className="flex items-center gap-2">
                         <button 
                            onClick={clearComparison}
                            className="text-xs font-medium text-slate-400 hover:text-white transition-colors px-3 py-2 rounded-lg hover:bg-slate-800"
                        >
                            Clear
                        </button>
                        <button 
                            onClick={() => setIsComparing(true)}
                            className="bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-bold py-2.5 px-6 rounded-full shadow-lg shadow-indigo-600/30 transition-all transform hover:scale-105 active:scale-95"
                        >
                            Compare Now
                        </button>
                    </div>
            </div>
        </div>
      )}

      {/* Modals */}
      {selectedTool && (
        <ToolDetailModal 
          tool={selectedTool} 
          onClose={handleCloseModal} 
          rating={ratings[selectedTool.name] || 0}
          onRate={(r) => handleRateTool(selectedTool.name, r)}
          isFavorite={favorites.includes(selectedTool.name)}
          onToggleFavorite={() => handleToggleFavorite(selectedTool.name)}
        />
      )}

      {isComparing && (
        <ComparisonModal 
            tools={comparisonList} 
            onClose={() => setIsComparing(false)} 
            ratings={ratings}
        />
      )}

      {isAddModalOpen && (
        <AddToolModal
            onClose={() => setIsAddModalOpen(false)}
            onAdd={handleAddTool}
            existingCategories={categories}
        />
      )}
      
      <Footer />
    </div>
  );
};

export default App;
