import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="w-full text-center py-8 mt-16 bg-slate-900 text-slate-400 border-t-2 border-indigo-500">
      <p>&copy; {new Date().getFullYear()} AI-Generated Insights. All rights reserved.</p>
      <p className="text-sm opacity-80">Content generated by Google Gemini.</p>
    </footer>
  );
};

export default Footer;
